stages:
  - build

build:
  stage: build
  image: sacurio/debianpackager:0.2
  before_script:
    - 'apt-get update && apt-get install -y --no-install-recommends libglib2.0-dev libcairo2-dev libpango1.0-dev libgtk-3-dev xvfb xauth golang-github-atotto-clipboard-dev golang-github-kardianos-osext-dev golang-golang-x-crypto-dev golang-golang-x-net-dev golang-gopkg-check.v1-dev golang-logrus-dev golang-x-text-dev golang-github-onsi-ginkgo-dev golang-gomega-dev golang-goprotobuf-dev golang-websocket-dev'
    - "eval $(ssh-agent -s)"
    - 'ssh-add <(echo "$DEBIAN_PACKAGING_PRIVATE_KEY")'
    - mkdir -p ~/.ssh; chmod 700 ~/.ssh
    - 'echo -e "|1|sIXiBfTWErM/nOgnpL5P9rdelKk=|pE4928lM5+rGDCYjNn+Yo5jFipg= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIx8qF3puSAM1UAxc3ODJTNGrgwf8mET664pPfP/ZQgiMxTIKG8Ar8h1xxP52AyQoqTLpCWOPaBkUya2Q0+SZTg=" >> ~/.ssh/known_hosts'
    - 'echo -e "|1|2sb5M4s4CRFlFYvv90vdWG9vyyg=|AGJyZ+2uBC7mOWJ2xHsW0En4tcU= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIx8qF3puSAM1UAxc3ODJTNGrgwf8mET664pPfP/ZQgiMxTIKG8Ar8h1xxP52AyQoqTLpCWOPaBkUya2Q0+SZTg=" >> ~/.ssh/known_hosts'
    - chmod 644 ~/.ssh/known_hosts
    - mkdir ~/deps
    - scp -P 4242 'repo@debian.autonomia.digital:/home/repo/packages/upload/golang-github-gotk3-gotk3-dev*.deb' ~/deps
    - scp -P 4242 'repo@debian.autonomia.digital:/home/repo/packages/upload/golang-github-coyim-gotk3adapter-dev*.deb' ~/deps
    - scp -P 4242 'repo@debian.autonomia.digital:/home/repo/packages/upload/golang-github-cubiest-jibberjabber-dev*.deb' ~/deps
    - scp -P 4242 'repo@debian.autonomia.digital:/home/repo/packages/upload/golang-github-digitalautonomy-grumble-dev*.deb' ~/deps
    - scp -P 4242 'repo@debian.autonomia.digital:/home/repo/packages/upload/golang-github-wybiral-torgo-dev*.deb' ~/deps
    - dpkg -i ~/deps/*.deb
  only:
    - master
  script:
    - gbp buildpackage --git-ignore-branch --git-no-pristine-tar --no-sign
    - mkdir debian_build
    - 'cp ../*.{deb,dsc,changes,tar.xz} debian_build'
    - 'scp -P 4242 debian_build/*.{deb,dsc,changes,tar.xz} repo@debian.autonomia.digital:/home/repo/packages/upload'
    - 'echo "$DEPLOY_DEBIAN_GPG_PASSPHRASE" | ssh -p 4242 repo@debian.autonomia.digital /home/repo/bin/update_packages'
  artifacts:
    paths:
      - 'debian_build/*.deb'
      - 'debian_build/*.dsc'
      - 'debian_build/*.changes'
      - 'debian_build/*.tar.xz'
